name = "R1CS_demo"
version = "0.1.0"
defaultTargets = ["r1cs_demo"]

[[lean_lib]]
name = "R1CSDemo"

[[lean_exe]]
name = "r1cs_demo"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.17.0-rc1"
